# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

project 'Dr.Go Player.xcodeproj'
target 'Dr.Go Player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dr.Go Player
  pod 'FacebookCore'
  pod 'FacebookLogin'  

end
